version: 2.1
orbs:
        maven: circleci/maven@1.3.0
        codecov: codecov/codecov@3.2.2
        node: circleci/node@4.7.0

machine:
    java: 
        version: 'oraclejdk8'



jobs : 
        build-and-test:
                docker:
                        - image: cimg/openjdk:11.0
                steps: 
                        - checkout
                        - run:
                                name: Build
                                command: mvn -B -DskipTests clean package
                        - run:
                                name : Test
                                command : mvn test
                        - run:
                                name: Code Coverage
                                command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov


build-deploy:
        jobs:
                - build : 
                        filters: 
                                branches:
                                        only : main
workflows:
        build :
                jobs: 
                        - build-and-test
        upload-to-codecov:
                jobs:
                - node/test:
                        post-steps:
                        - codecov/upload
        maven_test:
                jobs:
                        - maven/test:
                                command: '-X verify'
       
        

                       
                       
                   
