version: 2.1
orbs:
        maven: circleci/maven@1.3.0
        codecov: codecov/codecov@3.2.2
        node: circleci/node@4.7.0

machine:
    java: 
        version: 'oraclejdk8'



jobs : 
        build-and-test:
                docker:
                        - image: cimg/openjdk:11.0
                steps: 
                        - checkout
                        - run:
                                name: Build
                                command: mvn -B -DskipTests clean package
                        - run:
                                name : Test
                                command : mvn test 
                        - run:
                                name: CheckStyle
                                command : mvn -DskipTests checkstyle:checkstyle   
                        - codecov/upload:
                                file: /target/site/jacoco/jacoco.xml
                        - run:
                                name: Generate javadoc
                                command: mvn -B -DskipTests javadoc:javadoc

                        - persist_to_workspace:
                                root: target/site/
                                paths: apidocs

        docs-deploy:
                        docker:
                                - image: node:8.10.0
                        steps:
                                - checkout
                                - attach_workspace:
                                        at: docs/
                                - add_ssh_keys:
                                        fingerprints:
                                        - "6e:eb:b8:6b:fa:69:24:60:1f:8d:6e:87:fb:57:94:b6"
                                - run:
                                        name: Install and configure dependencies
                                        command: |
                                                npm install -g --silent gh-pages@2.0.1
                                                git config user.email "imanehacen@outlook.fr"
                                                git config user.name "imanehacen"
                                - run:
                                        name: Deploy docs to gh-pages branch
                                        command: gh-pages  --dist docs/apidocs/

                                        
                                        
                                       
                                                



build-deploy:
        jobs:
                - build : 
                        filters: 
                                branches:
                                        only : main
workflows:
        build :
                jobs: 
                        - build-and-test
                       
                        - docs-deploy:
                                requires:
                                        - build-and-test
                                        
                                filters:
                                        branches:
                                                only: master
       
        
        maven_test:
                jobs:
                        - maven/test:
                                command: '-X verify'
                        
        

                       
                       
                   
