version: 2.1
orbs:
        maven: circleci/maven@1.3.0
        codecov: codecov/codecov@3.2.2

machine:
    java: 
        version: 'oraclejdk8'

steps: 

        run:
                name : test
                command : test
                steps: 
                        - uses: actions/checkout@master
                        - uses: codecov/codecov-action@v2 
                        - codecov/upload
                with:
                        files: ./coverage1.xml
                        flags: unittests # optional
                        name: codecov-umbrella # optional
                        fail_ci_if_error: true # optional (default = false)
                        verbose: true # optional (default = false)

jobs : 
        build-and-test:
                docker:
                        - image: cimg/openjdk:11.0
                steps: 
                        - checkout
                        - run:
                                name: Build
                                command: mvn -B -DskipTests clean package
                        - run:
                                name : test
                                command : mvn test
                        - run:
                                name: Code Coverage
                                command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov


build-deploy:
        jobs:
                - build : 
                        filters: 
                                branches:
                                        only : main
workflows:
        build :
                jobs: 
                        - build-and-test
        maven_test:
                jobs:
                        - maven/test:
                                command: '-X verify'
       
        

                       
                       
                   
