orbs:
        maven: circleci/maven@1.3.0
version: 2.1

machine:
    java:
        version: 'oraclejdk8'

steps: 
        run :  
                name : test
                command : test
        

build-deploy:
        jobs:
                - build : 
                        filters: 
                                branches:
                                        only : main
workflows:
        maven_test:
                jobs:
                        - maven/test:
                                command: '-X verify'

                        
