version: 2.1
orbs:
        maven: circleci/maven@1.3.0
        codecov: codecov/codecov@3.2.2
        node: circleci/node@4.7.0

machine:
    java: 
        version: 'oraclejdk8'



jobs : 
        build-and-test:
                docker:
                        - image: cimg/openjdk:11.0
                steps: 
                        - checkout
                        - run:
                                name: Build
                                command: mvn -B -DskipTests clean package
                        - run:
                                name : Test
                                command : mvn test
                        - run:
                                name: Code Coverage
                                command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov
                        - run:
                                name: Checkstyle
                                command: mvn -B -DskipTests checkstyle:checkstyle       
                        - run:
                                name: Changement badge
                                command: |
                                        errors=$(grep -o "severity=\"error\"" output/checkstyle-result.xml | wc -l || true);
                                        if [ $errors -lt 1 ]
                                        then
                                                curl https://badgen.net/badge/checkstyle/$errors%20Errors/green -o badge.svg;
                                        elif [ $errors -lt 20 ]
                                                then
                                                curl https://badgen.net/badge/checkstyle/$errors%20Errors/yellow -o badge.svg;
                                                else
                                                curl https://badgen.net/badge/checkstyle/$errors%20Errors/red -o badge.svg;
                                        fi;
                                        echo '. as $file
                                                | $json
                                                | (.files."badge.svg".content= $file + "\n" + .content)' > methods.jq;             
                                        echo '{"description" : "Badge checkstyle",
                                                "files": {
                                                        "badge.svg": {
                                                        "content": ""
                                                        }
                                                }
                                        }' > curl.json;
                                        jq -R -s --argfile json curl.json -f methods.jq badge.svg > content.json;
                                        curl -X PATCH -H "Accept: application/vnd.github.v3+json" \
                                        -u $GIT_NAME:$GIT_TOKEN \
                                        --data-binary "@content.json" \
                                        https://api.github.com/gists/2f5cbd5dde9c8c1e4fa78710184949ed
                                        # trouver grace à https://api.github.com/users/imanehacen/gists
                                        



build-deploy:
        jobs:
                - build : 
                        filters: 
                                branches:
                                        only : main
workflows:
        build :
                jobs: 
                        - build-and-test
        
        maven_test:
                jobs:
                        - maven/test:
                                command: '-X verify'
       
        

                       
                       
                   
