orbs:
        maven: circleci/maven@1.3.0
        codecov: codecov/codecov@3.2.2
version: 2.1

machine:
    java:
        version: 'oraclejdk8'

steps: 
- uses: actions/checkout@master
- uses: codecov/codecov-action@v2
run :  
                name : test
                command : test

     
        

build-deploy:
        jobs:
                - build : 
                        filters: 
                                branches:
                                        only : main
workflows:
        maven_test:
                jobs:
                        - maven/test:
                                command: '-X verify'

                   
