orbs:
        maven: circleci/maven@1.3.0
version: 2.1
build-deploy:
        jobs:
                - build : 
                        filters: 
                                branches:
                                        only : main
workflows:
        maven_test:
                jobs:
                        - maven/test:
                                command: '-X verify'

                        
